# Generated by Django 2.2.2 on 2020-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('cv', models.FileField(default='', upload_to='uploaded_files/', verbose_name='cyz.pdf')),
                ('coverletter', models.TextField()),
            ],
        ),
    ]
